# Generated by Django 4.0.3 on 2022-05-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_casa', models.CharField(max_length=50)),
                ('iluminacao', models.BooleanField(default=False)),
                ('ventilacao', models.IntegerField()),
            ],
        ),
    ]
