# Generated by Django 4.0.3 on 2022-05-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='nome_casa',
            new_name='comodo',
        ),
    ]
