# Generated by Django 4.0.3 on 2022-05-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_nome_casa_status_comodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comodo', models.CharField(max_length=50)),
                ('iluminacao', models.BooleanField(default=False)),
                ('ventilacao', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
