# Generated by Django 4.0.3 on 2023-04-18 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nome do Dispostivo'),
        ),
        migrations.AlterField(
            model_name='device',
            name='pwm',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='PWM'),
        ),
        migrations.AlterField(
            model_name='device',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.room', verbose_name='Cômodo'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.BooleanField(verbose_name='Status do Dispositivo'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Cômodo'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.BooleanField(verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='room',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
