# Generated by Django 4.0.3 on 2023-04-18 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_device_name_alter_device_pwm_alter_device_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='room',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='home.room', verbose_name='Cômodo'),
            preserve_default=False,
        ),
    ]
